import NavBar from "@/components/NavBar/NavBar";
import "./globals.css";
import CtaContainer from "@/containers/CtaContainer/CtaContainer";
import FooterContainer from "@/containers/FooterContainer/FooterContainer";

export const metadata = {
  title: "Главная страница",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <NavBar/>
        </header>
        <main>{children}</main>
        <footer>
          <CtaContainer/>
          <FooterContainer/>
        </footer>
      </body>
    </html>
  );
}
